apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.15.0
          command: ["/usr/bin/filebeat", "-e", "-strict.perms=false"]
          args: ["--modules", "kubernetes"]
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlibkubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: varrunkubernetes
              mountPath: /var/run/kubernetes
              readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlibkubelet
          hostPath:
            path: /var/lib/kubelet
        - name: varrunkubernetes
          hostPath:
            path: /var/run/kubernetes
