---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.0.0
          ports:
            - containerPort: 5601
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 500Mi
              cpu: 250m